### ISSUE TITLE
Add support for themes

### ISSUE THREAD

**Issue by voodoos** [panglesd/slipshow#3]
## Problem
The actual theme is inspired by Warsaw but it would be great to have a way to easily change or modify the theme, without tinkering with the distributed `css`.

## Naive suggestion
- Make the common `css` (in `src/css`) as neutral as possible.
- Add some pre-made themes like the actual Warsaw theme in a folder like `src/css/themes`.
- In the example include first the theme-agnostic `css`, then the chosen theme `css`, then the specialized `slipIntroduction.css`.
- Document the various classes that users would need to override to make their own theme.

**Comment by panglesd** [comment]
That is a good idea. Currently the css files need a lot to be tidied.

Currently, the "theme" `.css` would need to include:
- the contents of `theorem.css`: the css for the classes: 
  - `theorems`, 
  - `definition`, 
  - `example`, 
  - `block`, 
- the class `titre` (need to be renamed!)
- the class `slip-body-container`.

**Comment by panglesd** [comment]
Since dd884bae5bd2916b16c68cfdc8ca11233e29d552, there is an [entry](https://slipshow.readthedocs.io/en/latest/themes.html) in the doc about using and writing a theme. I will see if I want to have a default theme always loaded. If yes, I can have only one css file. Otherwise, I will have to split wisely the slip core and the theme.

For now, I close the issue and keep the default theme always loaded. Themes loaded on top will override the default values.
