### ISSUE TITLE
Binary release file got CPU arch wrong (says x86_64, but it's actually arm)

### ISSUE THREAD

**Issue by tddschn** [panglesd/slipshow#54]
Binary release file got CPU arch wrong (says x86_64, but it's actually arm).

https://github.com/panglesd/slipshow/releases/download/v0.0.32/slipshow-macos-x86_64.tar

It doesn't run on my Intel machine. :(

**Comment by tddschn** [comment]
file: `slipshow: Mach-O 64-bit executable arm64`

**Comment by panglesd** [comment]
Thanks a lot for the report, and sorry for the problem!

The macos release file is built by the CI, on github's machine "`macos-latest`". It seems that recently, `macos-latest` switched to being an arm machine: https://github.com/actions/runner-images/issues/9741

The fix for this is to build on `macos-13` (and also `macos-14` but advertise it as ARM!).

I'll try to fix the release tomorrow morning. Sorry about that again, and thanks for checking slipshow!

**Comment by panglesd** [comment]
I have updated the [release](https://github.com/panglesd/slipshow/releases/tag/v0.0.32), which now contains both the arm and the x86_64.

Thanks for the report, and let me know if this work! (So I can close the issue, I don't have a Mac to test...)

**Comment by tddschn** [comment]
Thank you for the update! 

I tried the 0.0.32 version, this time the arch is correct, but `--serve` option doesn't work on my Mac (as far as this issue is concerned, it should be closed. :) )

**Comment by tddschn** [comment]
```
$ slipshow prime-numbers.md --serve
Visit http://127.0.0.1:8080 to view your presentation, with auto-reloading on file changes.
compile: internal error, uncaught exception:
         Unix.Unix_error(Unix.EOPNOTSUPP, "inotify_init", "")
```
Here's the output when using --serve.

**Comment by panglesd** [comment]
Thanks!

Indeed, the mac bug for --serve and --watch is known and I'm working on it. I unfortunately expect it to take some time...

In the meantime, see [this answer](https://github.com/panglesd/slipshow/issues/56#issuecomment-2152077666) for a workaround to `--watch` using `fswatch`
